version: '3.8'

services:
  frontend-builder:
    build: 
      context: ./vuecmf-web/frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      - NODE_ENV=production
    networks:
      - vuecmf-network

  backend-manager:
    build: 
      context: ./vuecmf-go
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=ServBay.dev
      - DB_NAME=genzltd
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - vuecmf-network

  db-admin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=host.docker.internal
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=ServBay.dev
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - vuecmf-network
    profiles:
      - db-admin

networks:
  vuecmf-network:
    driver: bridge
