global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # MongoDB监控
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
    metrics_path: /metrics
    scrape_interval: 30s

  # PostgreSQL监控
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgresql:5432']
    metrics_path: /metrics
    scrape_interval: 30s

  # Redis监控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: /metrics
    scrape_interval: 30s

  # Neo4j监控
  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j:7474']
    metrics_path: /metrics
    scrape_interval: 30s

  # Elasticsearch监控
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: /_prometheus/metrics
    scrape_interval: 30s

  # Weaviate监控
  - job_name: 'weaviate'
    static_configs:
      - targets: ['weaviate:8080']
    metrics_path: /v1/metrics
    scrape_interval: 30s

  # API服务监控
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['host.docker.internal:9000']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'user-api'
    static_configs:
      - targets: ['host.docker.internal:9001']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'resume-api'
    static_configs:
      - targets: ['host.docker.internal:9002']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'company-api'
    static_configs:
      - targets: ['host.docker.internal:9003']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'job-api'
    static_configs:
      - targets: ['host.docker.internal:9004']
    metrics_path: /metrics
    scrape_interval: 30s
