version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: dao-mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: dao_password_2024
      MYSQL_DATABASE: dao_dev
      MYSQL_USER: dao_user
      MYSQL_PASSWORD: dao_password_2024
    ports:
      - "9506:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7.0-alpine
    container_name: dao-redis-local
    ports:
      - "9507:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
  redis_data:
