# 新建或修改此文件
root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ."  # 确保构建命令正确
  delay = 1000
  exclude_dir = ["tmp", "testdata"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = true

[color]
  build = "yellow"
  main = "green"
  runner = "blue"
  watcher = "magenta"

[log]
  time = false

[misc]
  clean_on_exit = false

[watcher]
  delete_delay = 200
  exclude = []
  follow_symlink = false
  interval = 100
