name: Deploy to Alibaba Cloud Production

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install npm dependencies
        run: npm install

      - name: Run Node.js tests
        run: npm test

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run Python tests
        run: python -m unittest discover

      - name: Build Docker images
        run: |
          docker build -t loomacrm-production ./looma_crm_future
          docker build -t zervigo-future-production ./zervigo_future
          # Add builds for DAO and Blockchain if they are separate Dockerfiles

      - name: Deploy to Alibaba Cloud
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALIBABA_CLOUD_HOST }}
          username: ${{ secrets.ALIBABA_CLOUD_USER }}
          key: ${{ secrets.ALIBABA_CLOUD_SSH_KEY }}
          script: |
            cd /opt/production/
            # Stop existing services
            docker-compose down
            # Pull new images (if using a registry)
            # docker pull loomacrm-production:latest
            # docker pull zervigo-future-production:latest
            # Start new services
            docker-compose up -d
            # Run health checks
            ./verify-production-deployment.sh